### ISSUE TITLE
Google API HTTP 502 error is logged as user error

### ISSUE THREAD

**Issue by ErikZigo** [keboola/google-drive-writer-bundle#2]
![image](https://cloud.githubusercontent.com/assets/1726727/13072475/db61e334-d499-11e5-92b1-fcb74caf59b6.png)

Exc ID: wr-google-drive-f51d1435081932eefa535b664ae40090

It should be application error, without logging response xml to event message

**Comment by MiroCillik** [comment]
zvyseny backoff a pridane lepsie error hlasky
