### ISSUE TITLE
Error: Call to a member function toArray() on null

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/google-drive-writer-bundle#8]
```
Trace
in Account.php line 270
```

https://connection.keboola.com/admin/utils/logs?file=2017/03/06/2017-03-06-06-04-34-58bcede276db7-exception
https://connection.keboola.com/admin/utils/logs?file=2017/03/06/2017-03-06-06-04-34-58bcede27c6ec-log

**Comment by MiroCillik** [comment]
writer je deprecated
